### PR TITLE
Added UML design

### PR DESCRIPTION
**Pull request by dan1994**

### CODE REVIEW

**Comment by dan1994** [comment]
I currently added a UML only for classes I'm building without other classes I might be using that already exist. @amitkit, Please go hard on me. I want to learn.
Also, tell me if the there's a better way than uploading images to the git repo...

**Comment by Roynecro97** [comment]
I'm not sure I understand how the `FileReader` and `FileWriter` are supposed to be used from the UML.
I'd expect the file reader/writer to work with plain text, decoding/encoding inside.
Also, might be worth adding parameter names. I'm assuming the `*Encoding` classes can be constructed from the content in the constructor that gets a `string`, but I'm not sure how the default constructors or the ones from an `std::vector<bool>` are used.

**Comment by dan1994** [comment]
The `FileReader` and `FileWriter` are only for encoded file handling. Plain text files require no special handling (just conversion  to `string`), and so I didn't make a class for them.
By parameters you mean arguments to functions? For specific classes, or everything?
As for the `*Encoding` constructors, the default one should create a canonical encoding, the `string` constructor builds an encoding from text and I believe the `std::vector<bool>` constructor was meant for constructing an encoding from an encoding file, though I'm not sure this should be the argument type. If you haven't already, I recommend reading the `requirements.md` file.

**Comment by Roynecro97** [comment]
> The `FileReader` and `FileWriter` are only for encoded file handling. Plain text files require no special handling (just conversion to `string`), and so I didn't make a class for them.

I meant that I thought the `FileReader` (for example) will get the encoded file and give back the decoded text. After reading the [requirements.md](https://github.com/dan1994/cpp--dane/blob/master/requirements.md) in `master` I think it's clearer why these classes are built this way. And after reading [requirements.md](https://github.com/dan1994/cpp--dane/blob/feature/dane3-design-the-solution-using-uml/docs/requirements.md) in this branch, did you consider having a class that represents the header and maybe something that wraps the encoded text, and use file streams to read and write?

> By parameters you mean arguments to functions? For specific classes, or everything?

Yes. In the `Encoding` classes' constructors.

> I'm not sure this should be the argument type.

Maybe a `map`?

**Comment by amitkit** [comment]
Did you make a simple use case diagram or something like it?
Im not really sure how the building of the bitmap is going to happen.

In general the building of this bitmap is the magic behind huffman, i think you are missing some classes (even a simple queue). Tell me if im wrong

**Comment by dan1994** [comment]
> I meant that I thought the `FileReader` (for example) will get the encoded file and give back the decoded text. After reading the [requirements.md](https://github.com/dan1994/cpp--dane/blob/master/requirements.md) in `master` I think it's clearer why these classes are built this way. And after reading [requirements.md](https://github.com/dan1994/cpp--dane/blob/feature/dane3-design-the-solution-using-uml/docs/requirements.md) in this branch, did you consider having a class that represents the header and maybe something that wraps the encoded text, and use file streams to read and write?

I'll try to think of something along these lines. I think the first thing to change is that instead of holding the filename as a member, I'll hold an `ifstream`/`ofstream` object, and then I'll overload the `<<` and `>>` operators. 
As to holding classes for the headers, I meant to encapsulate this in the `FileReader` and `FileWriter` classes, but especially since 2 classes use these headers, it makes sense to put them in separate classes.

> Yes. In the `Encoding` classes' constructors.

> Maybe a `map`?

I'll add arg names and change the type to `BiMap` which seems the most appropriate.

**Comment by dan1994** [comment]
> Did you make a simple use case diagram or something like it?

I will make a diagram

> Im not really sure how the building of the bitmap is going to happen.
> 
> In general the building of this bitmap is the magic behind huffman, i think you are missing some classes (even a simple queue). Tell me if im wrong

The "magic" is in the `*Encoding` class that builds the `BiMap`, and can theoretically be implemented for any kind of encoding. 
In the case of Huffman encoding, I'll be needing a min heap and a prefix-less binary tree. I'll update my UML accordingly.

**Comment by dan1994** [comment]
@amitkit, @Roynecro97 Hey guys!
So Iv'e updated my design (a lot!)
Also migrated to plantuml at @Roynecro97's suggestion, which allows me to manage the UML as source.
I'm merging this PR for now, since I already spent a long time, consulted a lot with @narad-git. If you have any comments or questions let's do that in a different issue.
I would of course love to hear your thoughts!

**Pull request merged**
